#!/bin/bash
set -e

args="$@"
function log {
	echo "# [laser_beams] $args"
}
function process_cleanup {
	log 'Cleaning up background processes...'
	set +e
	jobs -p | xargs kill
	log 'done.'
	exit 0
}
trap process_cleanup SIGINT

report=scotty.report

cat > $report << EOF
# Starting scotty, please be patient...
# Command will be: $args
# Follow log files at scotty.log
EOF

${0%/*}/scotty $args >/dev/null 2>/dev/null &

while true; do
	clear
#	echo "[$(date)] Every 15.0s: [$(ls -l --full-time $report | cut -d' ' -f6-8)] cat $report"
	echo "[$(date)] Every 15.0s: [] cat $report"
	cat $report
	sleep 15
done

