#!/bin/bash
set -e

function log {
	echo "# [laser_beams] $@"
}
function process_cleanup {
	log 'Cleaning up background processes...'
	set +e
	jobs -p | xargs kill
	log 'done.'
	exit 0
}
trap process_cleanup SIGINT

report=scotty.report

cat > $report << EOF
# Starting scotty, please be patient...
# Follow log files at scotty.log
EOF

${0%/*}/scotty $@ >/dev/null 2>/dev/null &

while true; do
	clear
	echo "[$(date)] Every 15.0s: cat $report"
	cat $report
	sleep 15
done

