#!/bin/bash
set -e

testCommand="grails test-app $@"
testRunLogFile=scotty.log
reportOutput=scotty.report
junitReportXml=target/test-reports/TESTS-TestSuites.xml

function log {
	echo "# [scotty] $@" >> $testRunLogFile
}
function removeOldReport {
	log "removing old report..."
	mv $junitReportXml $junitReportXml.bak
}
removeOldReport

while true; do
	log "starting test loop..."
	log "running command: $testCommand"
	$testCommand | tee $testRunLogFile

	# check that test report file exists
	if [ -f $junitReportXml ]; then
		log "processing junit report xml at $junitReportXml..."
		${0%/*}/dr.eval $junitReportXml > $reportOutput
		removeOldReport
	else
		log "reporting build failure..."
		tail $testRunLogFile > $reportOutput
	fi
done

